app:
  image: debian:jessie
  volumes:
    - ./:/usr/share/nginx/
  tty: true
php:
  build: ./docker/php/
  ports:
    - "9000:9000"
  volumes_from:
    - app
  links:
    - mysql
nginx:
  build: ./docker/nginx/
  ports:
    - "8000:80"
  links:
    - php
    - mysql
  volumes_from:
    - app
mysql:
  image: mysql:5.6
  ports:
    - 33060:3306
  volumes:
    - "./docker/mysql/conf.d:/etc/mysql/conf.d"
    - "./docker/mysql/init:/docker-entrypoint-initdb.d"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes_from:
    - app
